### ISSUE TITLE
weight file mismatch with the model

### ISSUE THREAD

**Issue by yt2639** [Media-Smart/vedatad#14]
Hii thanks a lot for your work and sharing the code. I'm having trouble loading the weights file. So at the very beginning, it could not be loaded and then I used #10 suggested method and it worked. But then, I had this "unexpected keys" and "missing keys" issues. 
![image](https://user-images.githubusercontent.com/46978474/140001180-d4f1b592-b862-4c14-8eae-e3be50ef5b07.png)

I only changed num_classes = 1 in the second section "2. model" as I want to retrain the model on my dataset. But even if I changed it back to num_classes = 20, it's still having the same problem.

Could you help me with it? Thanks!

**Comment by haritha91** [comment]
I guess that's normal. Model training should be proceed even the weights are not matched.

**Comment by yt2639** [comment]
> I guess that's normal. Model training should be proceed even the weights are not matched.

@haritha91  Ohh yes thanks! It seems still running but it's stuck on iterating the dataloader so I thought it was dead. Well now comes the new question - how long would it be to iterate one batch given the default settings (4 GPUs, samples_per_gpu=4)?

Basically, my program is stuck 


```
class EpochBasedLooper(BaseLooper):

    def epoch_loop(self, mode):
        self.mode = mode
        dataloader = self.dataloaders[mode]
        engine = self.engines[mode]
        # print(type(engine))
        print('start batches!') # THIS LINE IS PRINTED
        for idx, data in enumerate(dataloader): # I stuck here!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
            print('start batch {}'.format(idx + 1)) # THIS LINE IS **NOT** PRINTED
            self.hook_pool.fire(f'before_{mode}_iter', self)
            self.cur_results[mode] = engine(data)
            if mode == BaseLooper.TRAIN:
                self._iter += 1
            self._inner_iter = idx + 1
            self.hook_pool.fire(f'after_{mode}_iter', self)
            print('finish batch {}'.format(idx+1))
```

It takes forever to iterate 1 batch. How long would this iterating generally take?

Many thanks!

**Comment by zzysteve** [comment]
> Basically, my program is stuck
> 
> ```
> class EpochBasedLooper(BaseLooper):
> 
>     def epoch_loop(self, mode):
>         self.mode = mode
>         dataloader = self.dataloaders[mode]
>         engine = self.engines[mode]
>         # print(type(engine))
>         print('start batches!') # THIS LINE IS PRINTED
>         for idx, data in enumerate(dataloader): # I stuck here!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
>             print('start batch {}'.format(idx + 1)) # THIS LINE IS **NOT** PRINTED
>             self.hook_pool.fire(f'before_{mode}_iter', self)
>             self.cur_results[mode] = engine(data)
>             if mode == BaseLooper.TRAIN:
>                 self._iter += 1
>             self._inner_iter = idx + 1
>             self.hook_pool.fire(f'after_{mode}_iter', self)
>             print('finish batch {}'.format(idx+1))
> ```
> 
> It takes forever to iterate 1 batch. How long would this iterating generally take?
> 
> Many thanks!

@yt2639  I have the same question. Does your training proceed?

**Comment by yt2639** [comment]
@Stevezzy I just solved it. In my case, I have totally different classes than Thumos. So you have to edit the thumos14.py file in dataset folder - to make a new dataset Class.

**Comment by DesaleF** [comment]
Hello @yt2639 and @Stevezzy, I am in the same situation. But I am using the Thumos14 dataset. I follow all the instruction however when I start the training it freezes. I tried it with 4 gpus. Do you have any solution?

**Comment by zzysteve** [comment]
@DesaleF I created a new classes in vedatad/datasets to load my dataset, referring to thumos14.py. CLASSES variable mismatch seems to block training. Maybe also check configs/trainval/daotad/daotad_i3d_r50_e700_thumos14_rgb.py for dataset path.

**Comment by DesaleF** [comment]
@Stevezzy  Thank you so much for your response. Now the problem seems solved.
