### ISSUE TITLE
End-to-end training?

### ISSUE THREAD

**Issue by DesaleF** [Media-Smart/vedatad#16]
Hi @Media-Smart Thank you for your excellent work and clean implementation. I want to ask you if you trained the whole network end-to-end. As you have described in the paper one of the disadvantage of two stream methods is their difficulty of training end-to-end. As this work is not based on two-stream input, I am assuming you have trained the network end-to-end. So did you optimize the feature extractor network too when training your model?

**Comment by C-H-Wong** [comment]
Yes, end-to-end
