### ISSUE TITLE
Test Question

### ISSUE THREAD

**Issue by zstarN70** [Media-Smart/vedatad#2]
howdy，Read your paper, very admire, but have a few questions, hope you to answer. First of all, I ran the training model and measured several sets of epoch, but it is not consistent with the 53.8 in your paper. Is the **baseline** data obtained here?

1200epoch	1000	900	           800	700	          600	300	       200	         100
0.445	       0.448	0.455	0.456	0.457	0.45	       0.445	0.416	0.34

**Comment by html4396** [comment]
您好，拜读您的大作，非常敬佩。不过有一个问题想向您请教，我使用了您给训练好的modle，但是得到的ioU是0.479，与您在paper中的数据有点出入，还望您赐教。

**Comment by C-H-Wong** [comment]
Videos should be decoded into ".png" images, the related [shell commands](https://github.com/Media-Smart/vedatad/tree/main/configs/trainval/daotad#thumos14) are updated, please try again.

**Comment by zstarN70** [comment]
Thanks,Problem solved.

**Comment by zstarN70** [comment]
> 视频需解码为“.png”图片，相关[shell命令](https://github.com/Media-Smart/vedatad/tree/main/configs/trainval/daotad#thumos14)已更新，请重试。

Thanks,Problem solved
