### ISSUE TITLE
Question about training time

### ISSUE THREAD

**Issue by wjn922** [Media-Smart/vedatad#7]
Hi,
 
Thanks for your wonderful repo. It reports a very large epoch number in your paper. So I wonder the training time of the model. And how many GPUs do you use?

**Comment by C-H-Wong** [comment]
> Hi,
> 
> Thanks for your wonderful repo. It reports a very large epoch number in your paper. So I wonder the training time of the model. And how many GPUs do you use?

Hi!
 
As we mentioned [here](https://github.com/Media-Smart/vedatad/tree/main/configs/trainval/daotad#thumos14-1), 4 1080ti GPUs are used for training, and the training time is about 1.5 hours per 100 epochs on our server for Thumos14. DaoTAD shows the best performance after about 600~800 epochs training on Thumos14. We took the results of 700th epoch as the final results reported in our paper, and the training time is aound 10.5 hours.

**Comment by wjn922** [comment]
Thanks for your reply!
